"""fix quantity column in GroceryItem

Revision ID: 9bcbf82da55c
Revises: b8ea8ccc51c2
Create Date: 2023-02-28 08:38:44.724964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcbf82da55c'
down_revision = 'b8ea8ccc51c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
