"""create many to many

Revision ID: b8ea8ccc51c2
Revises: e8b424fdb4a1
Create Date: 2023-02-27 17:02:45.879533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ea8ccc51c2'
down_revision = 'e8b424fdb4a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery_item_stores',
    sa.Column('grocery_item_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grocery_item_id'], ['grocery_items.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('grocery_item_id', 'store_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grocery_item_stores')
    # ### end Alembic commands ###
